export const mockContent = [
  {
    id: 1,
    title: 'Introduction to Algebra',
    subject: 'Mathematics',
    description: 'Basic concepts of algebra including variables, equations, and functions.',
    fileUrl: 'https://example.com/files/algebra-intro.pdf',
    status: 'approved',
    startTime: '2024-01-15T09:00:00Z',
    endTime: '2024-01-15T10:30:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 2,
    title: 'Photosynthesis Process',
    subject: 'Biology',
    description: 'Detailed explanation of how plants convert light energy into chemical energy.',
    fileUrl: 'https://example.com/files/photosynthesis.pdf',
    status: 'pending',
    startTime: '2024-01-16T10:00:00Z',
    endTime: '2024-01-16T11:30:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 3,
    title: 'World War II Overview',
    subject: 'History',
    description: 'Comprehensive overview of World War II including major events and outcomes.',
    fileUrl: 'https://example.com/files/ww2-overview.pdf',
    status: 'rejected',
    startTime: '2024-01-14T14:00:00Z',
    endTime: '2024-01-14T15:30:00Z',
    rotationDuration: 90,
    rejectionReason: 'Content contains inaccurate historical facts'
  },
  {
    id: 4,
    title: 'Newton\'s Laws of Motion',
    subject: 'Physics',
    description: 'Explanation of the three fundamental laws of motion discovered by Isaac Newton.',
    fileUrl: 'https://example.com/files/newtons-laws.pdf',
    status: 'approved',
    startTime: '2024-01-17T11:00:00Z',
    endTime: '2024-01-17T12:30:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 5,
    title: 'Shakespeare\'s Hamlet Analysis',
    subject: 'English Literature',
    description: 'Character analysis and themes in Shakespeare\'s tragedy Hamlet.',
    fileUrl: 'https://example.com/files/hamlet-analysis.pdf',
    status: 'draft',
    startTime: '2024-01-18T13:00:00Z',
    endTime: '2024-01-18T14:30:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 6,
    title: 'Chemical Reactions',
    subject: 'Chemistry',
    description: 'Types of chemical reactions and their characteristics.',
    fileUrl: 'https://example.com/files/chemical-reactions.pdf',
    status: 'approved',
    startTime: '2024-01-19T09:30:00Z',
    endTime: '2024-01-19T11:00:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 7,
    title: 'Geography of Africa',
    subject: 'Geography',
    description: 'Physical and political geography of the African continent.',
    fileUrl: 'https://example.com/files/africa-geography.pdf',
    status: 'pending',
    startTime: '2024-01-20T10:30:00Z',
    endTime: '2024-01-20T12:00:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 8,
    title: 'Programming Fundamentals',
    subject: 'Computer Science',
    description: 'Introduction to programming concepts including variables, loops, and functions.',
    fileUrl: 'https://example.com/files/programming-fundamentals.pdf',
    status: 'rejected',
    startTime: '2024-01-21T14:30:00Z',
    endTime: '2024-01-21T16:00:00Z',
    rotationDuration: 90,
    rejectionReason: 'Code examples are outdated and use deprecated syntax'
  },
  {
    id: 9,
    title: 'Art History: Renaissance',
    subject: 'Art',
    description: 'Overview of the Renaissance period and its major artists and works.',
    fileUrl: 'https://example.com/files/renaissance-art.pdf',
    status: 'approved',
    startTime: '2024-01-22T11:30:00Z',
    endTime: '2024-01-22T13:00:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 10,
    title: 'Economic Systems',
    subject: 'Economics',
    description: 'Comparison of different economic systems and their characteristics.',
    fileUrl: 'https://example.com/files/economic-systems.pdf',
    status: 'draft',
    startTime: '2024-01-23T09:00:00Z',
    endTime: '2024-01-23T10:30:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 11,
    title: 'Spanish Verb Conjugation',
    subject: 'Spanish',
    description: 'Regular and irregular verb conjugations in Spanish.',
    fileUrl: 'https://example.com/files/spanish-verbs.pdf',
    status: 'pending',
    startTime: '2024-01-24T13:30:00Z',
    endTime: '2024-01-24T15:00:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 12,
    title: 'Music Theory Basics',
    subject: 'Music',
    description: 'Fundamental concepts of music theory including notes, scales, and chords.',
    fileUrl: 'https://example.com/files/music-theory.pdf',
    status: 'approved',
    startTime: '2024-01-25T10:00:00Z',
    endTime: '2024-01-25T11:30:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 13,
    title: 'Psychology of Learning',
    subject: 'Psychology',
    description: 'How people learn and different learning theories and methods.',
    fileUrl: 'https://example.com/files/learning-psychology.pdf',
    status: 'rejected',
    startTime: '2024-01-26T14:00:00Z',
    endTime: '2024-01-26T15:30:00Z',
    rotationDuration: 90,
    rejectionReason: 'Content lacks proper citations and references'
  },
  {
    id: 14,
    title: 'Environmental Science',
    subject: 'Science',
    description: 'Study of environmental systems and human impact on the environment.',
    fileUrl: 'https://example.com/files/environmental-science.pdf',
    status: 'draft',
    startTime: '2024-01-27T11:00:00Z',
    endTime: '2024-01-27T12:30:00Z',
    rotationDuration: 90,
    rejectionReason: null
  },
  {
    id: 15,
    title: 'Business Ethics',
    subject: 'Business',
    description: 'Ethical principles and decision-making in business environments.',
    fileUrl: 'https://example.com/files/business-ethics.pdf',
    status: 'pending',
    startTime: '2024-01-28T09:30:00Z',
    endTime: '2024-01-28T11:00:00Z',
    rotationDuration: 90,
    rejectionReason: null
  }
]